# Generated by Django 5.2.7 on 2025-10-05 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения регистрации'),
        ),
        migrations.AddField(
            model_name='user',
            name='should_update_password',
            field=models.BooleanField(default=True, verbose_name='Требуется обновление пароля'),
        ),
    ]
