# Generated by Django 5.2.7 on 2025-10-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsverification',
            name='request_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID запроса SMS'),
        ),
    ]
