---
- name: Install Python {{ python_version }}
  apt:
    name:
      - python{{ python_version }}
      - python{{ python_version }}-dev
      - python{{ python_version }}-venv
      - python{{ python_version }}-pip
    state: present
  when: ansible_os_family == "Debian"

- name: Create Python virtual environment
  command: "python{{ python_version }} -m venv {{ app_venv }}"
  args:
    creates: "{{ app_venv }}/bin/activate"
  become_user: "{{ app_user }}"

- name: Upgrade pip
  pip:
    name: pip
    state: latest
    virtualenv: "{{ app_venv }}"
    virtualenv_python: "python{{ python_version }}"
  become_user: "{{ app_user }}"

- name: Install Python requirements
  pip:
    requirements: "{{ app_home }}/requirements.txt"
    virtualenv: "{{ app_venv }}"
    virtualenv_python: "python{{ python_version }}"
  become_user: "{{ app_user }}"
  notify: restart django
