---
- name: Deploy Django Backend Application
  hosts: webservers
  become: yes
  gather_facts: yes
  
  vars:
    deploy_user: "{{ app_user }}"
    deploy_home: "{{ app_home }}"
    
  pre_tasks:
    - name: Update system packages
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == "Debian"
      
    - name: Install required system packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - python3-dev
          - build-essential
          - libpq-dev
          - nginx
          - supervisor
          - git
          - curl
          - htop
          - tree
        state: present
      when: ansible_os_family == "Debian"
      
    - name: Create application user
      user:
        name: "{{ app_user }}"
        group: "{{ app_group }}"
        home: "{{ app_home }}"
        shell: /bin/bash
        create_home: yes
        
    - name: Create application directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        mode: '0755'
      loop:
        - "{{ app_home }}"
        - "{{ app_home }}/logs"
        - "{{ app_home }}/static"
        - "{{ app_home }}/media"
        - "{{ app_home }}/backups"
        
  roles:
    - role: python
    - role: postgresql
    - role: redis
    - role: nginx
    - role: django_app
    - role: supervisor
    - role: ssl
    - role: monitoring
    - role: backup
    
  post_tasks:
    - name: Set proper permissions
      file:
        path: "{{ app_home }}"
        owner: "{{ app_user }}"
        group: "{{ app_group }}"
        recurse: yes
        
    - name: Restart services
      systemd:
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop:
        - nginx
        - supervisor
        - postgresql
        - redis-server
      when: ansible_os_family == "Debian"
      
    - name: Show deployment status
      debug:
        msg: "Django application deployed successfully on {{ inventory_hostname }}"
